/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetopedidopizzaria;

import java.io.File;
import java.io.PrintStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.Toolkit;


/**
 *
 * @author 182220008
 */
public class TelaPedido extends javax.swing.JFrame {

    
    DefaultTableModel modeloTabela;
    private String opcional;
    private float cbMassa=0, cbCheddar=0, cbChoc=0, cbOutros=0,valorTamanho=0;
    private Pedido pedido;

    public TelaPedido() {
        super("Pizzaria e borracharia O rato que ri");
        initComponents();
        pedido = new Pedido();
        modeloTabela = (DefaultTableModel) tabelaPedido.getModel();
    }

    public void calculaItem() {
        
        tfSubTotalPizza.setText(String.format("R$ %.2f", calculaSubtotalPizza())); 
        
    }

    public void limpaPizza() {
        tfSubTotalPizza.setText("");
        tfUnidades.setText("");
        rbtgSabor.clearSelection();
        rbtgTamanho.clearSelection();
        cbBordaCheddar.setSelected(false);
        cbMassaIntegral.setSelected(false);
        cbBordaChoc.setSelected(false);
        cbBordaCat.setSelected(false);
    }

    public void limpaPedido() {
        limpaPizza();
        tfNomeCliente.setText("");
        tfEndereco.setText("");
        tfTel.setText("");
        cbxCidade.setSelectedIndex(0);
        modeloTabela.getDataVector().clear();

    }
    public Item criaItem(){
        Item it = new Item();
        
        it.setSabor(rbtgSabor.getSelection().getActionCommand());
        it.setValor(calculaSubtotalPizza());
        it.setQuantidade(Integer.parseInt(tfUnidades.getText()));
        it.setTamanho(rbtgTamanho.getSelection().getActionCommand());
        
        if (cbMassaIntegral.isSelected()) {
            it.setMassaIntegral("Massa integral");
        } else if (cbBordaCheddar.isSelected()) {
            it.setBordaChedar("Borda cheddar");
        } else if (cbBordaChoc.isSelected()) {
            it.setBordaChocolate("Borda chocolate");
        } else if (cbBordaCat.isSelected()) {
            it.setOutro("Borda Catupiry");
        }
        
        return it;
        
    }

    public float calculaSubtotalPizza() {
       return (valorTamanho+cbMassa+cbCheddar+cbChoc+cbOutros) * Integer.parseInt(tfUnidades.getText());
        
    }
    public float calculaSubtotalPedido(){
        float valor = 0.0f;
        for(Item it : pedido.getListaItens()){
            valor += it.getValor();
        }
        return valor;
    }
    

    public void ExcluiItem() {
        int s = tabelaPedido.getSelectedRow();
        pedido.getListaItens().remove(s);
        modeloTabela.removeRow(s);
        
//        String sabElim = String.valueOf(tabelaPedido.getModel().getValueAt(tabelaPedido.getSelectedRow(),0));
//        modeloTabela.removeRow(tabelaPedido.getSelectedRow());
//        
//       // Item itElim = new Item();
//        for(Item itAtual : listaItens){
//            if(itAtual.getSabor() == sabElim){
//            itElim = itAtual;
//            
//        }
//        }
//        listaItens.remove(itElim);;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbtgSabor = new javax.swing.ButtonGroup();
        rbtgTamanho = new javax.swing.ButtonGroup();
        rbtPort = new javax.swing.JRadioButton();
        tfSubTotalPizza = new javax.swing.JTextField();
        rbtChoc = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        rbtPeq = new javax.swing.JRadioButton();
        rbtMed = new javax.swing.JRadioButton();
        rbtGran = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaPedido = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        lbItens = new javax.swing.JLabel();
        btExclui = new javax.swing.JButton();
        fecharPedido = new javax.swing.JButton();
        tfEndereco = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        cbMassaIntegral = new javax.swing.JCheckBox();
        cbBordaCheddar = new javax.swing.JCheckBox();
        cbBordaChoc = new javax.swing.JCheckBox();
        cbBordaCat = new javax.swing.JCheckBox();
        tfTel = new javax.swing.JTextField();
        lbOpcionais = new javax.swing.JLabel();
        lbImage1 = new javax.swing.JLabel();
        lbImage2 = new javax.swing.JLabel();
        lbImage3 = new javax.swing.JLabel();
        lbImage4 = new javax.swing.JLabel();
        cbxCidade = new javax.swing.JComboBox<>();
        lbImage5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rbtCalab = new javax.swing.JRadioButton();
        rbtFrango = new javax.swing.JRadioButton();
        lbTitulo = new javax.swing.JLabel();
        lbTituloPedido = new javax.swing.JLabel();
        lbLogo = new javax.swing.JLabel();
        lbNomeCliente = new javax.swing.JLabel();
        lbEndereco = new javax.swing.JLabel();
        lbTel = new javax.swing.JLabel();
        lbCidade = new javax.swing.JLabel();
        tfNomeCliente = new javax.swing.JTextField();
        tfUnidades = new javax.swing.JTextField();
        btCalcItem = new javax.swing.JButton();
        rbtMarg = new javax.swing.JRadioButton();
        btAddPed = new javax.swing.JButton();
        lbSubTotal = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfSubtotalPedido = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(Toolkit.getDefaultToolkit().getImage(TelaPedido.class.getResource("/projetopedidopizzaria/Imagens/LogoPizza.jpg")));
        setSize(new java.awt.Dimension(745, 740));

        rbtgSabor.add(rbtPort);
        rbtPort.setText("Portuguesa");
        rbtPort.setActionCommand("Portuguesa");
        rbtPort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtPortActionPerformed(evt);
            }
        });

        tfSubTotalPizza.setEditable(false);

        rbtgSabor.add(rbtChoc);
        rbtChoc.setText("Chocolate com morango");
        rbtChoc.setActionCommand("Chocolate com morango");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        rbtgTamanho.add(rbtPeq);
        rbtPeq.setText("Pequena");
        rbtPeq.setActionCommand("Pequena");
        rbtPeq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtPeqActionPerformed(evt);
            }
        });

        rbtgTamanho.add(rbtMed);
        rbtMed.setText("Média");
        rbtMed.setActionCommand("Média");
        rbtMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtMedActionPerformed(evt);
            }
        });

        rbtgTamanho.add(rbtGran);
        rbtGran.setText("Grande");
        rbtGran.setActionCommand("Grande");
        rbtGran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtGranActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(rbtPeq)
                .addGap(91, 91, 91)
                .addComponent(rbtMed)
                .addGap(93, 93, 93)
                .addComponent(rbtGran)
                .addContainerGap(97, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtPeq)
                    .addComponent(rbtMed)
                    .addComponent(rbtGran))
                .addContainerGap())
        );

        tabelaPedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Pizza", "Tamanho", "Unidades", "Preço"
            }
        ));
        jScrollPane1.setViewportView(tabelaPedido);

        jLabel1.setText("Tamanho");

        lbItens.setText("Itens");

        btExclui.setText("Excluir pizza");
        btExclui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluiActionPerformed(evt);
            }
        });

        fecharPedido.setText("Fechar pedido");
        fecharPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fecharPedidoActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cbMassaIntegral.setText("Massa Integral");
        cbMassaIntegral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMassaIntegralActionPerformed(evt);
            }
        });

        cbBordaCheddar.setText("Borda Cheddar");
        cbBordaCheddar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBordaCheddarActionPerformed(evt);
            }
        });

        cbBordaChoc.setText("Borda chocolate");
        cbBordaChoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBordaChocActionPerformed(evt);
            }
        });

        cbBordaCat.setText("Borda Catupiry");
        cbBordaCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBordaCatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(cbMassaIntegral)
                .addGap(49, 49, 49)
                .addComponent(cbBordaCheddar)
                .addGap(52, 52, 52)
                .addComponent(cbBordaCat)
                .addGap(50, 50, 50)
                .addComponent(cbBordaChoc)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbMassaIntegral)
                    .addComponent(cbBordaCheddar)
                    .addComponent(cbBordaChoc)
                    .addComponent(cbBordaCat))
                .addContainerGap())
        );

        tfTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTelActionPerformed(evt);
            }
        });

        lbOpcionais.setText("Opcionais");

        lbImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetopedidopizzaria/Imagens/pizzaCalabresa.jpg"))); // NOI18N
        lbImage1.setText("Image 1");

        lbImage2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetopedidopizzaria/Imagens/pizzafrangocat.jpg"))); // NOI18N
        lbImage2.setText("Image2");

        lbImage3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetopedidopizzaria/Imagens/pizzamarg.jpg"))); // NOI18N
        lbImage3.setText("Image 3");

        lbImage4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetopedidopizzaria/Imagens/pizzaport.jpg"))); // NOI18N
        lbImage4.setText("Image4");

        cbxCidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Porto Alegre", "Canoas", "Esteio", "Sapucaia do Sul", "São Leopoldo" }));

        lbImage5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetopedidopizzaria/Imagens/pizzachoc.jpg"))); // NOI18N
        lbImage5.setText("Image5");

        jLabel2.setText("Unidades");

        rbtgSabor.add(rbtCalab);
        rbtCalab.setText("Calabresa");
        rbtCalab.setActionCommand("Calabresa");

        rbtgSabor.add(rbtFrango);
        rbtFrango.setText("Frango com catupiry");
        rbtFrango.setActionCommand("Frango com catupiry");

        lbTitulo.setText("PIZZARIA E BORRACHARIA O RATO QUE RI");

        lbTituloPedido.setText("- Pedido - ");

        lbLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetopedidopizzaria/Imagens/LogoPizza.jpg"))); // NOI18N
        lbLogo.setText("Logo");

        lbNomeCliente.setText("Nome do cliente:");

        lbEndereco.setText("Endereço:");

        lbTel.setText("Telefone:");

        lbCidade.setText("Cidade:");

        btCalcItem.setText("Calcula item");
        btCalcItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCalcItemActionPerformed(evt);
            }
        });

        rbtgSabor.add(rbtMarg);
        rbtMarg.setText("Marguerita");
        rbtMarg.setActionCommand("Marguerita");

        btAddPed.setText("Adiciona ao pedido");
        btAddPed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddPedActionPerformed(evt);
            }
        });

        lbSubTotal.setText("SubTotal pizza R$");

        jLabel3.setText("Subtotal Pedido R$");

        tfSubtotalPedido.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btExclui)
                                .addGap(236, 236, 236)
                                .addComponent(fecharPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lbNomeCliente)
                                                .addComponent(lbEndereco))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(tfEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                                                .addComponent(tfNomeCliente)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lbImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                                            .addComponent(lbImage2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(56, 56, 56))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(rbtCalab)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(rbtFrango)
                                            .addGap(35, 35, 35)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lbImage3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(12, 12, 12)
                                                    .addComponent(rbtMarg)))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(48, 48, 48)
                                                    .addComponent(rbtPort)
                                                    .addGap(52, 52, 52))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(lbImage4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(34, 34, 34)))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(rbtChoc)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addComponent(lbImage5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(31, 31, 31))))
                                        .addComponent(lbTitulo)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(34, 34, 34)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lbTel)
                                                .addComponent(lbCidade))
                                            .addGap(29, 29, 29)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(cbxCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(tfTel, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(lbSubTotal)
                                            .addGap(40, 40, 40)
                                            .addComponent(tfSubTotalPizza, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(lbItens)
                                                .addComponent(jLabel2))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(tfUnidades, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(104, 104, 104)
                                            .addComponent(btCalcItem)))
                                    .addGap(172, 172, 172)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addGap(27, 27, 27)
                                            .addComponent(tfSubtotalPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 51, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGap(0, 0, Short.MAX_VALUE)
                                            .addComponent(btAddPed, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(41, 41, 41))))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 15, Short.MAX_VALUE)
                        .addComponent(lbLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(292, 292, 292)
                        .addComponent(lbTituloPedido)
                        .addGap(337, 337, 337))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(lbOpcionais)
                        .addGap(20, 20, 20)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(lbTitulo)
                        .addGap(18, 18, 18)
                        .addComponent(lbTituloPedido)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNomeCliente)
                    .addComponent(lbTel)
                    .addComponent(tfNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEndereco)
                    .addComponent(lbCidade)
                    .addComponent(tfEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbImage2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbImage3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbImage4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbImage5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtCalab)
                    .addComponent(rbtFrango)
                    .addComponent(rbtMarg)
                    .addComponent(rbtPort)
                    .addComponent(rbtChoc))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel1)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbOpcionais)
                        .addGap(39, 39, 39)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfUnidades, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCalcItem)
                    .addComponent(btAddPed))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSubTotal)
                    .addComponent(tfSubTotalPizza, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(tfSubtotalPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbItens)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btExclui)
                    .addComponent(fecharPedido))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtPortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtPortActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtPortActionPerformed

    private void tfTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTelActionPerformed

    private void btCalcItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCalcItemActionPerformed
        calculaItem();
        
        
        
        
        
    }//GEN-LAST:event_btCalcItemActionPerformed
    private void imprimePedido(){
        try(PrintStream ps = new PrintStream(new File("Pedido.txt"))){
            ps.println(pedido);
            JOptionPane.showMessageDialog(this, "Pedido impresso com sucesso!",getTitle(),JOptionPane.INFORMATION_MESSAGE);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "Houve um erro ao tentar o imprimir o pedido: \n"+e.getMessage(),getTitle(),JOptionPane.ERROR_MESSAGE);
        }
        
    }
    private void btAddPedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddPedActionPerformed
        
        pedido.addItem(criaItem());

        modeloTabela.getDataVector().clear();
         for (Item it : pedido.getListaItens()){
             modeloTabela.addRow(new Object[] {it.getSabor(),it.getTamanho(),it.getQuantidade(),it.getValor()});            
        }
         limpaPizza();
         tfSubtotalPedido.setText(String.valueOf(calculaSubtotalPedido()));
    }//GEN-LAST:event_btAddPedActionPerformed

    private void fecharPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fecharPedidoActionPerformed
         
        pedido.setCliente(tfNomeCliente.getText());
        pedido.setEndereco(tfEndereco.getText());
        pedido.setTelefone(tfTel.getText());
        pedido.setCidade(cbxCidade.getSelectedItem().toString());
        imprimePedido();
        limpaPedido();
        
        pedido = new Pedido();
            

    }//GEN-LAST:event_fecharPedidoActionPerformed

    private void cbMassaIntegralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMassaIntegralActionPerformed
        cbMassa =  8.00f;
    }//GEN-LAST:event_cbMassaIntegralActionPerformed

    private void cbBordaCheddarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBordaCheddarActionPerformed
        cbCheddar = 6.00f;
    }//GEN-LAST:event_cbBordaCheddarActionPerformed

    private void cbBordaChocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBordaChocActionPerformed
        cbChoc = 6.50f;
    }//GEN-LAST:event_cbBordaChocActionPerformed

    private void cbBordaCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBordaCatActionPerformed
        cbOutros = 8.50f;
    }//GEN-LAST:event_cbBordaCatActionPerformed

    private void rbtPeqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtPeqActionPerformed
        valorTamanho = 40.00f;
    }//GEN-LAST:event_rbtPeqActionPerformed

    private void rbtMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtMedActionPerformed
        valorTamanho = 50.00f;
    }//GEN-LAST:event_rbtMedActionPerformed

    private void rbtGranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtGranActionPerformed
        valorTamanho = 60.00f;
    }//GEN-LAST:event_rbtGranActionPerformed

    private void btExcluiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluiActionPerformed
        ExcluiItem();
    }//GEN-LAST:event_btExcluiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPedido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAddPed;
    private javax.swing.JButton btCalcItem;
    private javax.swing.JButton btExclui;
    private javax.swing.JCheckBox cbBordaCat;
    private javax.swing.JCheckBox cbBordaCheddar;
    private javax.swing.JCheckBox cbBordaChoc;
    private javax.swing.JCheckBox cbMassaIntegral;
    private javax.swing.JComboBox<String> cbxCidade;
    private javax.swing.JButton fecharPedido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbCidade;
    private javax.swing.JLabel lbEndereco;
    private javax.swing.JLabel lbImage1;
    private javax.swing.JLabel lbImage2;
    private javax.swing.JLabel lbImage3;
    private javax.swing.JLabel lbImage4;
    private javax.swing.JLabel lbImage5;
    private javax.swing.JLabel lbItens;
    private javax.swing.JLabel lbLogo;
    private javax.swing.JLabel lbNomeCliente;
    private javax.swing.JLabel lbOpcionais;
    private javax.swing.JLabel lbSubTotal;
    private javax.swing.JLabel lbTel;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JLabel lbTituloPedido;
    private javax.swing.JRadioButton rbtCalab;
    private javax.swing.JRadioButton rbtChoc;
    private javax.swing.JRadioButton rbtFrango;
    private javax.swing.JRadioButton rbtGran;
    private javax.swing.JRadioButton rbtMarg;
    private javax.swing.JRadioButton rbtMed;
    private javax.swing.JRadioButton rbtPeq;
    private javax.swing.JRadioButton rbtPort;
    private javax.swing.ButtonGroup rbtgSabor;
    private javax.swing.ButtonGroup rbtgTamanho;
    private javax.swing.JTable tabelaPedido;
    private javax.swing.JTextField tfEndereco;
    private javax.swing.JTextField tfNomeCliente;
    private javax.swing.JTextField tfSubTotalPizza;
    private javax.swing.JTextField tfSubtotalPedido;
    private javax.swing.JTextField tfTel;
    private javax.swing.JTextField tfUnidades;
    // End of variables declaration//GEN-END:variables
}
